title: Pinku Deb Nath
description: My adventures on a beautiful planet floating in space.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
baseurl: /

exclude: ['README.md']


github_username: prantoran
linkedin_username: pinku-deb-nath-850a3975
google_plus_username: +PinkuDebNath
facebook_username: prantoran
google_scholar_citation_username: AmfLmlAAAAAJ
